# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gener8s < Formula
  desc "Generate source code for unstructured Kubernetes Go types from yaml manifests."
  homepage "https://github.com/nukleros/gener8s"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nukleros/gener8s/releases/download/v0.2.0/gener8s_v0.2.0_darwin_x86_64.tar.gz"
      sha256 "de07f64e4b63eff41234815f39e87b3bb7e4d33db5a55571ee85cbd2f21186b9"

      def install
        bin.install "gener8s"
      end
    end
    on_arm do
      url "https://github.com/nukleros/gener8s/releases/download/v0.2.0/gener8s_v0.2.0_darwin_arm64.tar.gz"
      sha256 "92698b59d074cc84593da7e1c68d78d2732441f7f1562666a35204ebfefa84c0"

      def install
        bin.install "gener8s"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/gener8s/releases/download/v0.2.0/gener8s_v0.2.0_linux_x86_64.tar.gz"
        sha256 "456bffc649a0905731c51830d2b9946fb22fb32c69ccf5b83125f8a85e0e29da"

        def install
          bin.install "gener8s"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/gener8s/releases/download/v0.2.0/gener8s_v0.2.0_linux_arm64.tar.gz"
        sha256 "8a60b07bede62d4ff131009b690bcc9edfb0d3f9082923fd3a0846ab91468db3"

        def install
          bin.install "gener8s"
        end
      end
    end
  end
end
