# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gener8s < Formula
  desc "Generate source code for unstructured Kubernetes Go types from yaml manifests."
  homepage "https://github.com/nukleros/gener8s"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nukleros/gener8s/releases/download/v0.3.0/gener8s_v0.3.0_darwin_x86_64.tar.gz"
      sha256 "f0c258e4d4f6f4e507ef5da84d8acf05a3bd2ecfcf78a1b152af7c218d504eb2"

      def install
        bin.install "gener8s"
      end
    end
    on_arm do
      url "https://github.com/nukleros/gener8s/releases/download/v0.3.0/gener8s_v0.3.0_darwin_arm64.tar.gz"
      sha256 "d205cfac9af6da7b847b7f9b6c9c209fd748e8e1341aa693cd914b59a5f092b1"

      def install
        bin.install "gener8s"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/gener8s/releases/download/v0.3.0/gener8s_v0.3.0_linux_x86_64.tar.gz"
        sha256 "d78581b7585ce6e721a254d00acf90451b4ba58176420709c3aa732e19bef4b7"

        def install
          bin.install "gener8s"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/gener8s/releases/download/v0.3.0/gener8s_v0.3.0_linux_arm64.tar.gz"
        sha256 "2dc885fa070a497252c5df76d742101fd65d477cffd6b48b4cf75756bb2c3198"

        def install
          bin.install "gener8s"
        end
      end
    end
  end
end
