# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/nukleros/operator-builder"
  version "0.10.0"
  license "MIT"

  depends_on "kubectl"
  depends_on "golang"
  depends_on "make" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.10.0/operator-builder_v0.10.0_Darwin_arm64.tar.gz"
      sha256 "5e9aa6d7cad8f5071432359975e918c4970a6860cb98a583e586cc2f56580626"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.10.0/operator-builder_v0.10.0_Darwin_x86_64.tar.gz"
      sha256 "235331ef2df452068aab706d56a04c11f311205723164e92aca709a5e3fd9d94"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.10.0/operator-builder_v0.10.0_Linux_x86_64.tar.gz"
      sha256 "6a0a7b3f28c3cd1eaf68ceb332ceda5acb897fb6ee9c6887f9b4a3aeeadf166f"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.10.0/operator-builder_v0.10.0_Linux_arm64.tar.gz"
      sha256 "f503ca32694eecafc59f773cd475a649ca44b0d3937e0da525f9c94fc0cab8d4"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  test do
    system "#{bin}/operator-builder version"
  end
end
