# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/nukleros/operator-builder"
  version "0.9.0"
  license "MIT"

  depends_on "kubectl"
  depends_on "golang"
  depends_on "make" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.9.0/operator-builder_v0.9.0_Darwin_arm64.tar.gz"
      sha256 "cd4be6f34683ba4c119039e2a135ab09aa645a13fa7b417d08e7fe14a140b487"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.9.0/operator-builder_v0.9.0_Darwin_x86_64.tar.gz"
      sha256 "288e93c159e833a634468bc5df5b0bc8e164bec287d933906254b155950becd8"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.9.0/operator-builder_v0.9.0_Linux_arm64.tar.gz"
      sha256 "5c1f2fd51fc7de1ff621b36f81a7a06c153568703d4a836842a138d2ce93600f"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nukleros/operator-builder/releases/download/v0.9.0/operator-builder_v0.9.0_Linux_x86_64.tar.gz"
      sha256 "e4740395ed6c1c24405b407b8fc983ff343a47244262b584e0eb69a409f16a73"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  test do
    system "#{bin}/operator-builder version"
  end
end
