# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OperatorBuilder < Formula
  desc "A Kubebuilder plugin to accelerate the development of Kubernetes operators."
  homepage "https://github.com/nukleros/operator-builder"
  version "0.11.0"
  license "MIT"

  depends_on "golang"
  depends_on "kubectl"
  depends_on "make" => :optional

  on_macos do
    on_intel do
      url "https://github.com/nukleros/operator-builder/releases/download/v0.11.0/operator-builder_v0.11.0_darwin_x86_64.tar.gz"
      sha256 "e03e8d2f841cb3d6189058837b62496d57aa6078f509412298709a5a45c499c0"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
    on_arm do
      url "https://github.com/nukleros/operator-builder/releases/download/v0.11.0/operator-builder_v0.11.0_darwin_arm64.tar.gz"
      sha256 "4cc51898208dc0e820317704bd2731d3e80ca8338d3de9f190e6838cdd84d1bc"

      def install
        bin.install "operator-builder"
        bash_completion.install "completions/operator-builder.bash" => "operator-builder"
        zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
        fish_completion.install "completions/operator-builder.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/operator-builder/releases/download/v0.11.0/operator-builder_v0.11.0_linux_x86_64.tar.gz"
        sha256 "160b1eb23253d5a3903d9590f24c78089fa43474cdc6fb1ca45d0bef4d93dc84"

        def install
          bin.install "operator-builder"
          bash_completion.install "completions/operator-builder.bash" => "operator-builder"
          zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
          fish_completion.install "completions/operator-builder.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nukleros/operator-builder/releases/download/v0.11.0/operator-builder_v0.11.0_linux_arm64.tar.gz"
        sha256 "4f2115c4c7ce628f69ca96911f361127366f40fa15b11b02ae0262f2a08e08ce"

        def install
          bin.install "operator-builder"
          bash_completion.install "completions/operator-builder.bash" => "operator-builder"
          zsh_completion.install "completions/operator-builder.zsh" => "_operator-builder"
          fish_completion.install "completions/operator-builder.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/operator-builder version"
  end
end
